networks:
  school-net:
    driver: bridge
    name: school-network

volumes:
  db-vol:
    driver: local
    name: database_volume

services:
  api:
    image: "node:20.12"
    container_name: "main-api"
    command: "npm run start-dev"
    working_dir: "/usr/app"
    volumes: 
      - "$PWD:/usr/app"
    ports:
      - "8080:8000"
    networks:
      - school-net

  school-database:
    image: "postgres:16.2"
    container_name: "database"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DATABASE}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    networks:
      - school-net
    volumes:
      - db-vol:/var/lib/postgresql/data

