networks:
  school-panel:
    driver: bridge
    name: school-panel

services:
  api:
    container_name: "api"
    image: "node:20.12"
    command: /bin/bash -c "yarn install && yarn run start"
    working_dir: "/usr/app"
    ports:
      - 8080:8000
    networks:
      - school-panel
    volumes:
      - "$PWD:/usr/app"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: "${POSTGRES_HOST}"
    image: "postgres:16.2"
    ports: 
      - 5432:5432
    networks:
      - school-panel
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT} -d ${POSTGRES_DB}"]
      interval: 7s
      timeout: 2s
      retries: 6

      


