networks:
  school-panel:
    driver: bridge
    name: school-panel

services:
  api:
    container_name: "api"
    image: "node:20.12"
    command: /bin/bash -c "yarn run start"
    working_dir: "/usr/app"
    ports:
      - 8080:8000
    networks:
      - school-panel
    volumes:
      - "$PWD:/usr/app"


