networks:
  school-network:
    driver: bridge
    name: school-network

services:
  api:
    image: "node:20.12"
    container_name: "main-api"
    command: "npm run start-dev"
    working_dir: "/usr/app"
    volumes: 
      - "$PWD:/usr/app"
    ports:
      - "8080:8000"
    networks:
      - school-network

  school-database:
    image: "postgres:16.2"
    container_name: "database"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DATABASE}"
      - "POSTGRES_USER=${POSTGRES_USER}"

